//State de productos
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const OBTENER_PRODUCTOS_MATSUSHIMA = "OBTENER_PRODUCTOS_MATSUSHIMA";
export const OBTENER_PRODUCTOS_TOMAOKA = "OBTENER_PRODUCTOS_TOMAOKA";
export const OBTENER_PRODUCTOS_HOSHINO = "OBTENER_PRODUCTOS_HOSHINO";
export const OBTENER_PRODUCTOS_OISHI = "OBTENER_PRODUCTOS_OISHI";
export const OBTENER_PRODUCTOS_OKAMOTO = "OBTENER_PRODUCTOS_OKAMOTO";
export const OBTENER_PRODUCTOS_YAMAKADO = "OBTENER_PRODUCTOS_YAMAKADO ";
export const OBTENER_PRODUCTOS_SKLAR = "OBTENER_PRODUCTOS_SKLAR";
export const OBTENER_PRODUCTOS_ENRIQUE = "OBTENER_PRODUCTOS_ENRIQUE";
export const OBTENER_PRODUCTOS_USER1 = "OBTENER_PRODUCTOS_USER1";
export const OBTENER_PRODUCTOS_USER2 = "OBTENER_PRODUCTOS_USER2";
export const OBTENER_PRODUCTOS_USER3 = "OBTENER_PRODUCTOS_USER3";

// State para el Pedido
export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const CONFIRMAR_ORDENAR_PLATILLO = "CONFIRMAR_ORDENAR_PLATILLO";
export const MOSTRAR_RESUMEN = "MOSTRAR_RESUMEN";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const PEDIDO_ORDENADO = "PEDIDO_ORDENADO";